### ISSUE TITLE
FR: commandline flag to only print private key

### ISSUE THREAD

**Issue by abliss** [moncho/warpwallet#1]
This would be handy for piping it to a wallet-importer without writing to disk, using the copy/paste buffer, or exposing through /proc/$pid/environ .

Thanks for the tool!

**Comment by moncho** [comment]
Hi, it is a nice idea :)

Something like `warpwallet --quiet` (with **-q** shortversion)?

**Comment by moncho** [comment]
Added to version [v0.1.2](https://github.com/moncho/warpwallet/releases/tag/v0.1.2).

**Comment by abliss** [comment]
Hi, thanks for the quick change! unfortunately, the prompts still go to stdout so the output is polluted. They should probably go to stderr instead.

**Comment by abliss** [comment]
(a workaround is to use a pipe as stdin, which suppresses the prompt.)
