### ISSUE TITLE
Possibly consider making this a package?

### ISSUE THREAD

**Issue by zLeki** [moncho/warpwallet#5]
Hi there, love warp wallet but it would be nice if it was publicly updated and maintained as a package rather then a full application. I created a fork with the code that I use as a package and if you could take a look that would be nice.

**Comment by zLeki** [comment]
Created the pull request. Thanks for responding as a package would be easier for most developers to use rather then having the full package in their working directory, as for myself at least.

**Comment by moncho** [comment]
Thanks for the PR @zLeki !! 

I like the idea of changing the layout so the code is easier to use outside, but the purpose of this repo is still having a command line tool. I have created a new PR (#7), please take a look at it and let me know what you think.
